### ISSUE TITLE
Just confused

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/adrv9009-zu11eg-fan-control-daemon#6]
Why not get the hwmon to iio bridge running, and just use the lm-sensors's fancontrol script?

https://help.ubuntu.com/community/SensorInstallHowto#Controlling_fanspeeds_according_to_sensor_values

Wouldn't that be a better option (less overall maintenance/documentation) that creating our own userspace?

https://linux.die.net/man/8/fancontrol

https://github.com/lm-sensors/lm-sensors/blob/master/doc/fancontrol.txt

https://github.com/lm-sensors/lm-sensors/blob/master/prog/pwm/fancontrol

**Comment by mhennerich** [comment]
This daemon does more than controlling the fan speed based on temperature sources.
There is also some fail mode handling, where we turn off the transceivers and also their clocks.
The IIO/HWMON bridge allows you to export voltage and temp channels into HWMON, but you can't control IIO device string attributes from HWMON. Given this we didn't consider the lm-sensors fancontrol a viable solution for this task.

**Comment by rgetz** [comment]
OK - expanded scope makes sense. Shouldn't we add that to the README?
